import argparse
import json
from pathlib import Path


DEFAULT_VARIANTS = ("clean", "speed_0.9", "speed_1.1", "noise_0.005")
AUTO = "auto"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Expand ASR manifests into pseudo-domains for SMEAR-MoE routing simulations."
    )
    parser.add_argument(
        "--input-dir",
        default="processed_data/manifests",
        help="Directory containing source split manifests generated by process_data.py.",
    )
    parser.add_argument( 
        "--output-dir",
        default="simulation_manifests",
        help="Directory where expanded manifests will be written.",
    )
    parser.add_argument(
        "--train-variants",
        default=",".join(DEFAULT_VARIANTS),
        help="Comma-separated augmentation variants to duplicate in the training split.",
    )
    parser.add_argument(
        "--eval-variants",
        default="clean",
        help="Comma-separated augmentation variants to duplicate in validation/test splits.",
    )
    parser.add_argument(
        "--splits",
        default="train,validation,test",
        help="Comma-separated split names to process if the files exist.",
    )
    parser.add_argument(
        "--language-tag",
        default=AUTO,
        help="Language tag fallback. Use 'auto' to prefer the record's 'language' field.",
    )
    return parser.parse_args()


def load_jsonl(path: Path) -> list[dict]:
    records: list[dict] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def write_jsonl(path: Path, records: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")


def normalize_variants(raw: str) -> list[str]:
    variants = [item.strip() for item in raw.split(",") if item.strip()]
    if not variants:
        raise ValueError("At least one variant is required.")
    return variants


def non_empty_string(value) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def infer_source_id(record: dict, index: int) -> str:
    record_id = non_empty_string(record.get("id"))
    if record_id:
        return record_id
    audio_path = non_empty_string(record.get("audio_filepath"))
    if audio_path:
        return Path(audio_path).stem
    return f"sample_{index:05d}"


def resolve_language_tag(record: dict, default_tag: str) -> str:
    record_language = non_empty_string(record.get("language"))
    if default_tag == AUTO:
        return record_language or "unknown"
    return record_language or default_tag


def infer_speaker_profile(record: dict) -> str:
    return (
        non_empty_string(record.get("speaker_id"))
        or non_empty_string(record.get("gender"))
        or "unknown"
    )


def expand_records(records: list[dict], split: str, variants: list[str], language_tag: str) -> list[dict]:
    expanded: list[dict] = []
    for index, record in enumerate(records):
        source_id = infer_source_id(record, index)
        speaker_profile = infer_speaker_profile(record)
        resolved_language = resolve_language_tag(record, language_tag)

        for variant in variants:
            item = dict(record)
            item["source_id"] = source_id
            item["id"] = f"{source_id}__{variant}"
            item["simulation_domain"] = variant
            item["pseudo_language"] = resolved_language
            item["routing_group"] = f"{resolved_language}::{speaker_profile}::{variant}"
            item["speaker_profile"] = speaker_profile
            item["is_augmented"] = variant != "clean"
            item["split"] = split
            expanded.append(item)
    return expanded


def main() -> None:
    args = parse_args()
    input_dir = Path(args.input_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    splits = [item.strip() for item in args.splits.split(",") if item.strip()]
    train_variants = normalize_variants(args.train_variants)
    eval_variants = normalize_variants(args.eval_variants)

    summary: dict[str, dict] = {}
    language_inventory: set[str] = set()
    for split in splits:
        source_path = input_dir / f"{split}.jsonl"
        if not source_path.exists():
            print(f"Skipping missing split manifest: {source_path}")
            continue

        variants = train_variants if split == "train" else eval_variants
        source_records = load_jsonl(source_path)
        expanded_records = expand_records(
            source_records,
            split=split,
            variants=variants,
            language_tag=args.language_tag,
        )
        for item in expanded_records:
            language_inventory.add(item.get("pseudo_language", "unknown"))
        output_path = output_dir / f"{split}.jsonl"
        write_jsonl(output_path, expanded_records)

        summary[split] = {
            "source_rows": len(source_records),
            "expanded_rows": len(expanded_records),
            "variants": variants,
            "language_tag": args.language_tag,
            "detected_languages": sorted(
                {item.get("pseudo_language", "unknown") for item in expanded_records}
            ),
        }
        print(f"[{split}] {len(source_records)} -> {len(expanded_records)} rows")

    summary_path = output_dir / "summary.json"
    with summary_path.open("w", encoding="utf-8") as handle:
        json.dump(
            {
                "splits": summary,
                "global_detected_languages": sorted(language_inventory),
            },
            handle,
            indent=2,
            ensure_ascii=False,
        )
    print(f"Simulation manifests saved to: {output_dir}")


if __name__ == "__main__":
    main()
